### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lololagar**
add comments

### CODE REVIEW

**Comment by juanitita** [comment]
yes i agree maybe add a few comments that will make readers understand better

**Comment by juanitita** [comment]
the code and the flowchart don't exactly match correctly , I would like to contribute and help with that

**Comment by lololagar** [comment]
any contributors?

**Comment by juanitita** [comment]
yes I would like to contribute with the flowchart and the code because I realized they don't exactly match and could use some work

**Pull request merged**
